[project]
name = "url-shortener"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "fastapi[standard]>=0.136.3",
    "sqlmodel>=0.0.38",
    "uvicorn>=0.48.0",
    "python-dotenv>=1.0.0",
    "psycopg2-binary>=2.9.6",
    "passlib>=1.7.4",
    "pydantic>=2.13.4",
    "typing>=3.10.0.0",
    "pyjwt>=2.13.0",
    "httpx>=0.28.1",
    "pytest>=9.1.0",
    "email-validator>=2.3.0",
    "redis>=8.0.1",
]
[tool.pytest.ini_options]
filterwarnings = [
    "ignore::Warning"
]
